# pydantic validation schemas
# this file is for API endpoint validation
# purpose of this file is to define the expected structure
# of the data that will be sent to and from the API endpoints,
# ensuring that the data adheres to the specified format and types.
# This helps in validating incoming requests and structuring outgoing responses
# in a consistent manner.

from pydantic import BaseModel, Field
from typing import List, Optional
from datetime import datetime

class ChatMessageRequest(BaseModel):
    """Validates the incoming message body payload from the client."""
    message: str = Field(..., description="The conversational text input from the user.")
    session_id: str = Field(..., description="A unique string identifier for this specific chat session.")

class ChatMessageResponseItem(BaseModel):
    """Represents a clean, serialized conversation turn returned in history arrays."""
    id: int
    role: str = Field(..., description="The speaker's identity: 'user', 'assistant', or 'system'.")
    content: str
    created_at: datetime

    class Config:
        from_attributes = True # allows API to read SQLAlchemy database items and organise them into JSON

class EvaluationBlock(BaseModel):
    """The strict inner self-evaluation matrix required for every agent response turn."""
    groundedness: float = Field(..., ge=0.0, le=1.0, description="Score from 0.0 to 1.0 reflecting factual accuracy against the catalog.")
    relevance: float = Field(..., ge=0.0, le=1.0, description="Score from 0.0 to 1.0 reflecting how well the prompt was addressed.")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Overall internal AI model certainty score.")
    flagged: bool = Field(..., description="True if confidence falls below the threshold, marking for human review.")
    reasoning: str = Field(..., description="A short textual deduction logging why these scores were assigned.")


class ChatAgentResponse(BaseModel):
    """The complete response payload returned by the POST /chat/{user_id} endpoint."""
    response: str = Field(..., description="The conversational textual response generated by the assistant.")
    eval: EvaluationBlock = Field(..., description="The validation metrics score block tracking execution accuracy.")
    tools_called: List[str] = Field(default_factory=list, description="A record tracking exactly which execution tools were invoked.")
    session_id: str = Field(..., description="The conversational session identifier linked to this turn.")